spring:
environment: test
varTest:
  test: 2
server:
  port: 1234
  output:
    ansi:
      enabled: ALWAYS
  logging:
    level:
      root: INFO

---
environment: prod
varProd:
  prod: 8
server:
  port: 8000
  output:
    ansi:
      enabled: ALWAYS
  logging:
    level:
      root: DEBUG

